export const appStyles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: '#1A1A1A',
    color: '#E0E0E0',
    fontFamily: 'Inter, system-ui, Avenir, Helvetica, Arial, sans-serif',
  },
  header: {
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '40px 24px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: '1px solid #424242',
    borderRadius: '12px 12px 0 0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    backgroundColor: '#212121',
  },
  title: {
    fontSize: '2rem',
    fontWeight: '800',
    letterSpacing: '-0.025em',
    color: '#FF7043',
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
  },
  main: {
    flex: 1,
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '24px',
    padding: '24px',
    border: '1px solid #424242',
    borderTop: 'none',
    backgroundColor: '#212121',
    position: 'relative' as const,
  },
  leftPanel: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '500px',
  },
  section: {
    flex: 1,
    overflow: 'hidden' as const,
    marginTop: '16px',
  },
  aside: {
    height: '500px',
  },
  pagination: {
    position: 'absolute' as const,
    bottom: '16px',
    left: '24px',
    right: '50%',
    display: 'flex',
    justifyContent: 'center',
  },
  errorButtonContainer: {
    position: 'fixed' as const,
    bottom: '32px',
    right: '32px',
    zIndex: 50,
  },
  errorButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#E53935',
    color: 'white',
    fontWeight: 'bold',
    padding: '12px 24px',
    borderRadius: '9999px',
    boxShadow: '0 10px 15px rgba(0,0,0,0.3)',
    fontSize: '1.125rem',
    transition: 'transform 0.15s',
    border: '4px solid #212121',
  },
  errorIcon: {
    width: '28px',
    height: '28px',
  },
};
